
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/4
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/4
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/4
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 4 processes
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 168, in <module>
    main()
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 164, in main
Traceback (most recent call last):
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 168, in <module>
    trainer.fit(model, datamodule=data)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _run
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _call_setup_hook
    main()
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 164, in main
    self.accelerator.barrier("pre_setup")
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 381, in barrier
    trainer.fit(model, datamodule=data)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self.training_type_plugin.barrier(name=name)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 356, in barrier
    self._run(model)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _run
    torch.distributed.barrier(device_ids=self.determine_ddp_device_ids())
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _call_setup_hook
    self.accelerator.barrier("pre_setup")
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 381, in barrier
    self.training_type_plugin.barrier(name=name)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 356, in barrier
    torch.distributed.barrier(device_ids=self.determine_ddp_device_ids())
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1631630841592/work/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
    work = default_pg.barrier(opts=opts)
Traceback (most recent call last):
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1631630841592/work/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 168, in <module>
    main()
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 164, in main
    trainer.fit(model, datamodule=data)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _run
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _call_setup_hook
    self.accelerator.barrier("pre_setup")
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 381, in barrier
    self.training_type_plugin.barrier(name=name)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 356, in barrier
    torch.distributed.barrier(device_ids=self.determine_ddp_device_ids())
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1631630841592/work/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
Traceback (most recent call last):
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 168, in <module>
    main()
  File "/scratch/roko/roko/multimodule_attn_tryitout.py", line 164, in main
    trainer.fit(model, datamodule=data)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _run
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _call_setup_hook
    self.accelerator.barrier("pre_setup")
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 381, in barrier
    self.training_type_plugin.barrier(name=name)
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 356, in barrier
    torch.distributed.barrier(device_ids=self.determine_ddp_device_ids())
  File "/scratch/miniconda3/envs/roko/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2538, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1631630841592/work/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
56720d87535c:26603:26603 [4] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.8<0>
56720d87535c:26603:26603 [4] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
56720d87535c:26603:26603 [4] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
56720d87535c:26603:26603 [4] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.8<0>
56720d87535c:26603:26603 [4] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda11.1
56720d87535c:26647:26647 [6] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.8<0>
56720d87535c:26647:26647 [6] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
56720d87535c:26647:26647 [6] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
56720d87535c:26647:26647 [6] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.8<0>
56720d87535c:26647:26647 [6] NCCL INFO Using network Socket
56720d87535c:26656:26656 [7] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.8<0>
56720d87535c:26656:26656 [7] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
56720d87535c:26656:26656 [7] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
56720d87535c:26656:26656 [7] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.8<0>
56720d87535c:26656:26656 [7] NCCL INFO Using network Socket
56720d87535c:26646:26646 [5] NCCL INFO Bootstrap : Using [0]eth0:172.17.0.8<0>
56720d87535c:26646:26646 [5] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
56720d87535c:26646:26646 [5] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
56720d87535c:26646:26646 [5] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.8<0>
56720d87535c:26646:26646 [5] NCCL INFO Using network Socket
56720d87535c:26647:26676 [6] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch
56720d87535c:26647:26676 [6] NCCL INFO graph/xml.cc:662 -> 2
56720d87535c:26647:26676 [6] NCCL INFO graph/topo.cc:523 -> 2
56720d87535c:26647:26676 [6] NCCL INFO init.cc:581 -> 2
56720d87535c:26646:26678 [5] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch
56720d87535c:26603:26675 [4] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch
56720d87535c:26647:26676 [6] NCCL INFO init.cc:840 -> 2
56720d87535c:26646:26678 [5] NCCL INFO graph/xml.cc:662 -> 2
56720d87535c:26603:26675 [4] NCCL INFO graph/xml.cc:662 -> 2
56720d87535c:26646:26678 [5] NCCL INFO graph/topo.cc:523 -> 2
56720d87535c:26603:26675 [4] NCCL INFO graph/topo.cc:523 -> 2
56720d87535c:26646:26678 [5] NCCL INFO init.cc:581 -> 2
56720d87535c:26603:26675 [4] NCCL INFO init.cc:581 -> 2
56720d87535c:26646:26678 [5] NCCL INFO init.cc:840 -> 2
56720d87535c:26647:26676 [6] NCCL INFO group.cc:73 -> 2 [Async thread]
56720d87535c:26603:26675 [4] NCCL INFO init.cc:840 -> 2
56720d87535c:26603:26675 [4] NCCL INFO group.cc:73 -> 2 [Async thread]
56720d87535c:26646:26678 [5] NCCL INFO group.cc:73 -> 2 [Async thread]
56720d87535c:26656:26677 [7] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch
56720d87535c:26656:26677 [7] NCCL INFO graph/xml.cc:662 -> 2
56720d87535c:26656:26677 [7] NCCL INFO graph/topo.cc:523 -> 2
56720d87535c:26656:26677 [7] NCCL INFO init.cc:581 -> 2
56720d87535c:26656:26677 [7] NCCL INFO init.cc:840 -> 2
56720d87535c:26656:26677 [7] NCCL INFO group.cc:73 -> 2 [Async thread]